const SPREADSHEET_ID="1ZE57tRpOIrj-jvouBTel4k78q4Wku4oi72H0iXZ-bCc";
let employees=[];let schedules=[];let currentMonth="2026-08";
document.addEventListener("DOMContentLoaded",()=>{setupNavigation();setupEvents();loadGoogleData();});
function loadGoogleSheet(sheetName,range){return new Promise((resolve,reject)=>{const callbackName="__haiSushi_"+Date.now()+"_"+Math.floor(Math.random()*100000);const script=document.createElement("script");const timeout=setTimeout(()=>{cleanup();reject(new Error(`讀取 ${sheetName} 逾時`));},15000);function cleanup(){clearTimeout(timeout);if(script.parentNode)script.parentNode.removeChild(script);try{delete window[callbackName]}catch(e){window[callbackName]=undefined}}window[callbackName]=response=>{cleanup();if(!response||response.status==="error"){reject(new Error("無法讀取 "+sheetName));return}resolve(response.table)};const url="https://docs.google.com/spreadsheets/d/"+SPREADSHEET_ID+"/gviz/tq?sheet="+encodeURIComponent(sheetName)+"&range="+encodeURIComponent(range)+"&headers=1&tqx="+encodeURIComponent("out:json;responseHandler:"+callbackName);script.src=url;script.onerror=()=>{cleanup();reject(new Error("無法載入 "+sheetName))};document.body.appendChild(script);});}
async function loadGoogleData(){showLoading(true);setStatus("loading","正在同步 Google Sheet...");try{const[employeeTable,scheduleTable]=await Promise.all([loadGoogleSheet("員工設定","A2:D300"),loadGoogleSheet("多人班表","A2:K3010")]);employees=parseEmployees(employeeTable);schedules=parseSchedules(scheduleTable);buildMonthOptions();buildEmployeeOptions();renderAll();const now=new Date().toLocaleString("zh-TW");setStatus("online","Google Sheet 已連線");setText("lastSync",`最後同步：${now}`);setText("syncMessage",`同步完成：${now}`)}catch(error){console.error(error);setStatus("error","Google Sheet 讀取失敗");setText("syncMessage",error.message);alert("Google Sheet 無法讀取。\n\n請確認 Google Sheet 分享權限為：\n知道連結的任何人 → 檢視者")}finally{showLoading(false)}}
function getCell(row,index){if(!row||!row.c||!row.c[index])return"";const cell=row.c[index];if(cell.f!==undefined&&cell.f!==null)return String(cell.f).trim();if(cell.v!==undefined&&cell.v!==null)return String(cell.v).trim();return""}
function parseEmployees(table){if(!table||!Array.isArray(table.rows))return[];return table.rows.map((row,index)=>{const name=getCell(row,0),hourlyRate=Number(getCell(row,1))||0,overtimeRate=Number(getCell(row,2))||1,enabledText=getCell(row,3).toUpperCase();return{id:index+1,name,hourlyRate,overtimeRate,enabled:enabledText==="TRUE"||enabledText==="1"||enabledText==="是"}}).filter(e=>e.name&&e.enabled)}
function parseSchedules(table){if(!table||!Array.isArray(table.rows))return[];return table.rows.map(row=>({date:normalizeDate(getCell(row,0)),name:getCell(row,1),start:normalizeTime(getCell(row,2)),end:normalizeTime(getCell(row,3)),breakHours:toNumber(getCell(row,4)),totalHours:toNumber(getCell(row,5)),normalHours:toNumber(getCell(row,6)),overtimeHours:toNumber(getCell(row,7)),status:getCell(row,8),note:getCell(row,9),manualBreak:getCell(row,10)})).filter(item=>item.date&&item.name)}
function normalizeDate(value){if(!value)return"";let text=String(value).trim();const googleDate=text.match(/Date\((\d+),(\d+),(\d+)/);if(googleDate){const year=Number(googleDate[1]),month=Number(googleDate[2])+1,day=Number(googleDate[3]);return year+"-"+String(month).padStart(2,"0")+"-"+String(day).padStart(2,"0")}text=text.replace(/-/g,"/");const parts=text.split("/");if(parts.length!==3)return"";const year=Number(parts[0]),month=Number(parts[1]),day=Number(parts[2]);if(!year||!month||!day)return"";return year+"-"+String(month).padStart(2,"0")+"-"+String(day).padStart(2,"0")}
function normalizeTime(value){if(!value)return"";const text=String(value);const match=text.match(/(\d{1,2}):(\d{2})/);if(!match)return text;return String(Number(match[1])).padStart(2,"0")+":"+match[2]}
function toNumber(value){const number=Number(String(value||0).replace(/,/g,""));return Number.isFinite(number)?number:0}
function getAvailableMonths(){const set=new Set();schedules.forEach(item=>{if(item.date)set.add(item.date.substring(0,7))});if(set.size===0)set.add(currentMonth);return Array.from(set).sort()}
function buildMonthOptions(){const months=getAvailableMonths();if(!months.includes(currentMonth))currentMonth=months[months.length-1];["globalMonth","scheduleMonth"].forEach(id=>{const select=document.getElementById(id);select.innerHTML="";months.forEach(value=>{const[year,month]=value.split("-").map(Number);const option=document.createElement("option");option.value=value;option.textContent=`${year} 年 ${month} 月`;select.appendChild(option)});select.value=currentMonth})}
function buildEmployeeOptions(){const filter=document.getElementById("employeeFilter"),personal=document.getElementById("personalEmployee");filter.innerHTML='<option value="all">全部人員</option>';personal.innerHTML="";employees.forEach(employee=>{const a=document.createElement("option");a.value=employee.name;a.textContent=employee.name;filter.appendChild(a);const b=document.createElement("option");b.value=employee.name;b.textContent=employee.name;personal.appendChild(b)})}
function monthSchedules(){return schedules.filter(item=>item.date.startsWith(currentMonth))}
function employeeStats(name){const rows=monthSchedules().filter(item=>item.name===name);return{shifts:rows.length,normalHours:rows.reduce((s,r)=>s+r.normalHours,0),overtimeHours:rows.reduce((s,r)=>s+r.overtimeHours,0),totalHours:rows.reduce((s,r)=>s+r.totalHours,0)}}
function renderAll(){renderDashboard();renderSchedule();renderPersonal();renderHours();renderEmployees()}
function renderDashboard(){const rows=monthSchedules(),names=new Set(rows.map(r=>r.name)),total=rows.reduce((s,r)=>s+r.totalHours,0),overtime=rows.reduce((s,r)=>s+r.overtimeHours,0);setText("activeCount",`${names.size} 人`);setText("totalHours",`${total.toFixed(1)} 小時`);setText("totalShifts",`${rows.length} 班`);setText("totalOvertime",`${overtime.toFixed(1)} 小時`);const tbody=document.getElementById("dashboardTable");tbody.innerHTML="";employees.forEach(e=>{const s=employeeStats(e.name);tbody.innerHTML+=`<tr><td><strong>${escapeHtml(e.name)}</strong></td><td>${s.shifts}</td><td>${s.normalHours.toFixed(1)}</td><td>${s.overtimeHours.toFixed(1)}</td><td><strong>${s.totalHours.toFixed(1)}</strong></td></tr>`});renderRecent()}
function renderRecent(){const c=document.getElementById("recentList");c.innerHTML="";const rows=[...monthSchedules()].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);if(!rows.length){c.innerHTML='<div class="recent-item">本月尚無資料</div>';return}rows.forEach(r=>{c.innerHTML+=`<div class="recent-item"><div><div class="recent-name">${escapeHtml(r.name)}</div><div class="recent-info">${displayDate(r.date)}</div></div><div class="recent-info">${escapeHtml(r.start)} ～ ${escapeHtml(r.end)}<br>${r.totalHours.toFixed(1)} 小時</div></div>`})}
function renderSchedule(){const head=document.getElementById("scheduleHead"),body=document.getElementById("scheduleBody");head.innerHTML="";body.innerHTML="";const[year,month]=currentMonth.split("-").map(Number),days=new Date(year,month,0).getDate(),header=document.createElement("tr"),first=document.createElement("th");first.textContent="人員 / 日期";header.appendChild(first);for(let day=1;day<=days;day++){const date=new Date(year,month-1,day),th=document.createElement("th"),week=["日","一","二","三","四","五","六"][date.getDay()];th.innerHTML=`${day}<br><small>${week}</small>`;if(date.getDay()===0||date.getDay()===6)th.classList.add("weekend");header.appendChild(th)}head.appendChild(header);const filter=document.getElementById("employeeFilter").value,search=document.getElementById("searchEmployee").value.trim();employees.filter(e=>(filter==="all"||e.name===filter)&&e.name.includes(search)).forEach(e=>{const tr=document.createElement("tr"),nameCell=document.createElement("td");nameCell.className="employee-cell";nameCell.innerHTML=`<div class="avatar">${escapeHtml(e.name.charAt(0))}</div><div class="employee-name"><strong>${escapeHtml(e.name)}</strong><small>$${e.hourlyRate}/h</small></div>`;tr.appendChild(nameCell);for(let day=1;day<=days;day++){const td=document.createElement("td");td.className="shift-cell";const dateKey=currentMonth+"-"+String(day).padStart(2,"0"),shift=schedules.find(i=>i.name===e.name&&i.date===dateKey);if(!shift)td.innerHTML='<span class="empty">—</span>';else{const ot=shift.overtimeHours>0;td.innerHTML=`<div class="shift-box ${ot?"overtime":""}"><div class="shift-time">${escapeHtml(shift.start)} ～ ${escapeHtml(shift.end)}</div><div class="shift-break">休 ${shift.breakHours.toFixed(1)}h</div><div class="shift-total">${shift.totalHours.toFixed(1)}h ${ot?`＋${shift.overtimeHours.toFixed(1)}`:""}</div></div>`}tr.appendChild(td)}body.appendChild(tr)})}
function renderPersonal(){const select=document.getElementById("personalEmployee");if(!select.value&&employees.length)select.value=employees[0].name;const name=select.value,tbody=document.getElementById("personalTable");tbody.innerHTML="";if(!name)return;const rows=monthSchedules().filter(i=>i.name===name).sort((a,b)=>a.date.localeCompare(b.date));rows.forEach(r=>{tbody.innerHTML+=`<tr><td>${displayDate(r.date)}</td><td>${escapeHtml(r.start)}</td><td>${escapeHtml(r.end)}</td><td>${r.breakHours.toFixed(1)}</td><td>${r.normalHours.toFixed(1)}</td><td>${r.overtimeHours.toFixed(1)}</td><td><strong>${r.totalHours.toFixed(1)}</strong></td><td>${escapeHtml(r.note)}</td></tr>`});const s=employeeStats(name);document.getElementById("personalStats").innerHTML=`<div class="small-card"><span>班次</span><strong>${s.shifts}</strong></div><div class="small-card"><span>正常工時</span><strong>${s.normalHours.toFixed(1)}</strong></div><div class="small-card"><span>加班工時</span><strong>${s.overtimeHours.toFixed(1)}</strong></div><div class="small-card"><span>總工時</span><strong>${s.totalHours.toFixed(1)}</strong></div>`}
function renderHours(){const rows=monthSchedules(),total=rows.reduce((s,r)=>s+r.totalHours,0),normal=rows.reduce((s,r)=>s+r.normalHours,0),overtime=rows.reduce((s,r)=>s+r.overtimeHours,0);setText("statTotal",`${total.toFixed(1)} 小時`);setText("statNormal",`${normal.toFixed(1)} 小時`);setText("statOvertime",`${overtime.toFixed(1)} 小時`);setText("statShifts",`${rows.length} 班`);const tbody=document.getElementById("hoursTable");tbody.innerHTML="";employees.forEach(e=>{const s=employeeStats(e.name);tbody.innerHTML+=`<tr><td><strong>${escapeHtml(e.name)}</strong></td><td>$${e.hourlyRate}</td><td>${s.shifts}</td><td>${s.normalHours.toFixed(1)}</td><td>${s.overtimeHours.toFixed(1)}</td><td><strong>${s.totalHours.toFixed(1)}</strong></td></tr>`})}
function renderEmployees(){const c=document.getElementById("employeeCards");c.innerHTML="";employees.forEach(e=>{c.innerHTML+=`<div class="employee-card"><div class="employee-top"><div class="employee-big-avatar">${escapeHtml(e.name.charAt(0))}</div><div><h3>${escapeHtml(e.name)}</h3><small>啟用中</small></div></div><div class="employee-row"><span>時薪</span><strong>$${e.hourlyRate}</strong></div><div class="employee-row"><span>加班倍率</span><strong>${e.overtimeRate}</strong></div></div>`})}
function setupNavigation(){document.querySelectorAll(".nav-btn").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".nav-btn").forEach(i=>i.classList.remove("active"));button.classList.add("active");document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(button.dataset.page).classList.add("active")}))}
function setupEvents(){document.getElementById("globalMonth").addEventListener("change",e=>{currentMonth=e.target.value;document.getElementById("scheduleMonth").value=currentMonth;renderAll()});document.getElementById("scheduleMonth").addEventListener("change",e=>{currentMonth=e.target.value;document.getElementById("globalMonth").value=currentMonth;renderAll()});document.getElementById("employeeFilter").addEventListener("change",renderSchedule);document.getElementById("searchEmployee").addEventListener("input",renderSchedule);document.getElementById("personalEmployee").addEventListener("change",renderPersonal);["refreshBtn","scheduleRefresh","syncBtn"].forEach(id=>document.getElementById(id).addEventListener("click",loadGoogleData))}
function setStatus(status,text){const dot=document.getElementById("statusDot");dot.className="status-dot";if(status==="online")dot.classList.add("online");if(status==="error")dot.classList.add("error");setText("connectionText",text)}
function showLoading(show){document.getElementById("loading").classList.toggle("show",show)}
function setText(id,text){const el=document.getElementById(id);if(el)el.textContent=text}
function displayDate(value){if(!value)return"";const parts=value.split("-");return Number(parts[1])+"/"+Number(parts[2])}
function escapeHtml(value){if(value===null||value===undefined)return"";return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}